version: '3.9'

networks:
  crm-network:

services:
  database:
    image: mysql:5.7.16
    container_name: crm-db
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
      MYSQL_DATABASE: "crm"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - crm-network